# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pageWindow.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PageWindow(object):
    def setupUi(self, PageWindow):
        PageWindow.setObjectName("PageWindow")
        PageWindow.resize(792, 676)
        self.centralwidget = QtWidgets.QWidget(PageWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 761, 281))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 721, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sourcepath = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.sourcepath.setObjectName("sourcepath")
        self.horizontalLayout.addWidget(self.sourcepath)
        self.browseButton = QtWidgets.QToolButton(self.horizontalLayoutWidget)
        self.browseButton.setObjectName("browseButton")
        self.horizontalLayout.addWidget(self.browseButton)
        self.listword = QtWidgets.QListWidget(self.groupBox)
        self.listword.setGeometry(QtCore.QRect(20, 70, 721, 192))
        self.listword.setObjectName("listword")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 320, 761, 321))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pagetable = QtWidgets.QTableWidget(self.groupBox_2)
        self.pagetable.setGeometry(QtCore.QRect(20, 30, 721, 241))
        self.pagetable.setRowCount(1)
        self.pagetable.setObjectName("pagetable")
        self.pagetable.setColumnCount(2)
        item = QtWidgets.QTableWidgetItem()
        self.pagetable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.pagetable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.pagetable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        self.pagetable.setItem(0, 1, item)
        self.pagetable.horizontalHeader().setDefaultSectionSize(101)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 280, 721, 31))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.totalpage = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.totalpage.setObjectName("totalpage")
        self.horizontalLayout_2.addWidget(self.totalpage)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(20, 293, 761, 31))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.executeButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_3)
        self.executeButton.setObjectName("executeButton")
        self.horizontalLayout_3.addWidget(self.executeButton)
        PageWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PageWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 792, 23))
        self.menubar.setObjectName("menubar")
        PageWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PageWindow)
        self.statusbar.setObjectName("statusbar")
        PageWindow.setStatusBar(self.statusbar)

        self.retranslateUi(PageWindow)
        QtCore.QMetaObject.connectSlotsByName(PageWindow)

    def retranslateUi(self, PageWindow):
        _translate = QtCore.QCoreApplication.translate
        PageWindow.setWindowTitle(_translate("PageWindow", "统计Word文档页码"))
        self.groupBox.setTitle(_translate("PageWindow", "源"))
        self.label.setText(_translate("PageWindow", "请选择Word文档所在目录："))
        self.browseButton.setText(_translate("PageWindow", "..."))
        self.groupBox_2.setTitle(_translate("PageWindow", "结果"))
        item = self.pagetable.horizontalHeaderItem(0)
        item.setText(_translate("PageWindow", "文件名"))
        item = self.pagetable.horizontalHeaderItem(1)
        item.setText(_translate("PageWindow", "页码"))
        __sortingEnabled = self.pagetable.isSortingEnabled()
        self.pagetable.setSortingEnabled(False)
        self.pagetable.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("PageWindow", "合计页码："))
        self.totalpage.setText(_translate("PageWindow", "未统计"))
        self.executeButton.setText(_translate("PageWindow", "开始统计"))

