# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'window.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(960, 600)
        MainWindow.setMinimumSize(QtCore.QSize(960, 600))
        MainWindow.setMaximumSize(QtCore.QSize(960, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 960, 600))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabBar::tab{width:320;height:50;}")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_query = QtWidgets.QWidget()
        self.tab_query.setObjectName("tab_query")
        self.widget_query = QtWidgets.QWidget(self.tab_query)
        self.widget_query.setGeometry(QtCore.QRect(0, 0, 960, 51))
        self.widget_query.setStyleSheet("QWidget#widget_query{background-color: rgb(212, 212, 212);}")
        self.widget_query.setObjectName("widget_query")
        self.label_4 = QtWidgets.QLabel(self.widget_query)
        self.label_4.setGeometry(QtCore.QRect(30, 20, 54, 12))
        self.label_4.setObjectName("label_4")
        self.textEdit = QtWidgets.QTextEdit(self.widget_query)
        self.textEdit.setGeometry(QtCore.QRect(80, 10, 104, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.label_5 = QtWidgets.QLabel(self.widget_query)
        self.label_5.setGeometry(QtCore.QRect(220, 20, 54, 12))
        self.label_5.setObjectName("label_5")
        self.textEdit_2 = QtWidgets.QTextEdit(self.widget_query)
        self.textEdit_2.setGeometry(QtCore.QRect(270, 10, 104, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setObjectName("textEdit_2")
        self.label_6 = QtWidgets.QLabel(self.widget_query)
        self.label_6.setGeometry(QtCore.QRect(410, 20, 54, 12))
        self.label_6.setObjectName("label_6")
        self.textEdit_3 = QtWidgets.QTextEdit(self.widget_query)
        self.textEdit_3.setGeometry(QtCore.QRect(460, 10, 104, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setObjectName("textEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.widget_query)
        self.pushButton.setGeometry(QtCore.QRect(610, 10, 91, 31))
        self.pushButton.setObjectName("pushButton")
        self.widget_checkBox = QtWidgets.QWidget(self.tab_query)
        self.widget_checkBox.setGeometry(QtCore.QRect(0, 50, 960, 35))
        self.widget_checkBox.setAutoFillBackground(False)
        self.widget_checkBox.setStyleSheet("QWidget#widget_checkBox{background-color: rgb(212, 212, 212);}")
        self.widget_checkBox.setObjectName("widget_checkBox")
        self.checkBox_T = QtWidgets.QCheckBox(self.widget_checkBox)
        self.checkBox_T.setGeometry(QtCore.QRect(572, 9, 63, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_T.setFont(font)
        self.checkBox_T.setObjectName("checkBox_T")
        self.checkBox_K = QtWidgets.QCheckBox(self.widget_checkBox)
        self.checkBox_K.setGeometry(QtCore.QRect(730, 9, 63, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_K.setFont(font)
        self.checkBox_K.setObjectName("checkBox_K")
        self.checkBox_Z = QtWidgets.QCheckBox(self.widget_checkBox)
        self.checkBox_Z.setGeometry(QtCore.QRect(415, 9, 63, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_Z.setFont(font)
        self.checkBox_Z.setObjectName("checkBox_Z")
        self.checkBox_D = QtWidgets.QCheckBox(self.widget_checkBox)
        self.checkBox_D.setGeometry(QtCore.QRect(258, 9, 63, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_D.setFont(font)
        self.checkBox_D.setObjectName("checkBox_D")
        self.checkBox_G = QtWidgets.QCheckBox(self.widget_checkBox)
        self.checkBox_G.setGeometry(QtCore.QRect(100, 9, 70, 17))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_G.setFont(font)
        self.checkBox_G.setObjectName("checkBox_G")
        self.label_type_2 = QtWidgets.QLabel(self.widget_checkBox)
        self.label_type_2.setGeometry(QtCore.QRect(30, 9, 65, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_type_2.setFont(font)
        self.label_type_2.setObjectName("label_type_2")
        self.label_train_img = QtWidgets.QLabel(self.tab_query)
        self.label_train_img.setGeometry(QtCore.QRect(0, 86, 960, 62))
        self.label_train_img.setText("")
        self.label_train_img.setPixmap(QtGui.QPixmap(":/png/table_img.png"))
        self.label_train_img.setObjectName("label_train_img")
        self.tableView = QtWidgets.QTableView(self.tab_query)
        self.tableView.setGeometry(QtCore.QRect(0, 145, 960, 401))
        self.tableView.setObjectName("tableView")
        self.tabWidget.addTab(self.tab_query, "")
        self.tab_analysis = QtWidgets.QWidget()
        self.tab_analysis.setObjectName("tab_analysis")
        self.widget_query_2 = QtWidgets.QWidget(self.tab_analysis)
        self.widget_query_2.setGeometry(QtCore.QRect(0, 0, 960, 51))
        self.widget_query_2.setStyleSheet("QWidget#widget_query{background-color: rgb(212, 212, 212);}")
        self.widget_query_2.setObjectName("widget_query_2")
        self.label_7 = QtWidgets.QLabel(self.widget_query_2)
        self.label_7.setGeometry(QtCore.QRect(80, 20, 54, 12))
        self.label_7.setObjectName("label_7")
        self.textEdit_analysis_from = QtWidgets.QTextEdit(self.widget_query_2)
        self.textEdit_analysis_from.setGeometry(QtCore.QRect(130, 10, 104, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textEdit_analysis_from.setFont(font)
        self.textEdit_analysis_from.setObjectName("textEdit_analysis_from")
        self.label_8 = QtWidgets.QLabel(self.widget_query_2)
        self.label_8.setGeometry(QtCore.QRect(270, 20, 54, 12))
        self.label_8.setObjectName("label_8")
        self.textEdit_analysis_to = QtWidgets.QTextEdit(self.widget_query_2)
        self.textEdit_analysis_to.setGeometry(QtCore.QRect(320, 10, 104, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textEdit_analysis_to.setFont(font)
        self.textEdit_analysis_to.setObjectName("textEdit_analysis_to")
        self.pushButton_analysis_query = QtWidgets.QPushButton(self.widget_query_2)
        self.pushButton_analysis_query.setGeometry(QtCore.QRect(460, 10, 91, 31))
        self.pushButton_analysis_query.setObjectName("pushButton_analysis_query")
        self.label_16 = QtWidgets.QLabel(self.widget_query_2)
        self.label_16.setGeometry(QtCore.QRect(750, 20, 20, 20))
        self.label_16.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.label_16.setText("")
        self.label_16.setObjectName("label_16")
        self.label_18 = QtWidgets.QLabel(self.widget_query_2)
        self.label_18.setGeometry(QtCore.QRect(820, 20, 20, 20))
        self.label_18.setStyleSheet("background-color: rgb(85, 170, 0);")
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.label_14 = QtWidgets.QLabel(self.widget_query_2)
        self.label_14.setGeometry(QtCore.QRect(660, 20, 20, 20))
        self.label_14.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.label_14.setText("")
        self.label_14.setObjectName("label_14")
        self.label_19 = QtWidgets.QLabel(self.widget_query_2)
        self.label_19.setGeometry(QtCore.QRect(850, 20, 51, 20))
        self.label_19.setObjectName("label_19")
        self.label_15 = QtWidgets.QLabel(self.widget_query_2)
        self.label_15.setGeometry(QtCore.QRect(690, 20, 51, 20))
        self.label_15.setObjectName("label_15")
        self.label_17 = QtWidgets.QLabel(self.widget_query_2)
        self.label_17.setGeometry(QtCore.QRect(780, 20, 51, 20))
        self.label_17.setObjectName("label_17")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_analysis)
        self.tableWidget.setGeometry(QtCore.QRect(0, 50, 953, 241))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tableWidget.setFont(font)
        self.tableWidget.setStyleSheet("QHeaderView{font:16pt \'楷体\';};\n"
"")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_analysis)
        self.scrollArea_2.setGeometry(QtCore.QRect(0, 290, 955, 255))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 953, 253))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents_2)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 951, 251))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.tabWidget.addTab(self.tab_analysis, "")
        self.tab_time = QtWidgets.QWidget()
        self.tab_time.setObjectName("tab_time")
        self.widget_time = QtWidgets.QWidget(self.tab_time)
        self.widget_time.setGeometry(QtCore.QRect(0, 0, 960, 551))
        self.widget_time.setStyleSheet("QWidget#widget_time{background-image: url(:/png/time_bg.png);}")
        self.widget_time.setObjectName("widget_time")
        self.label_time_text = QtWidgets.QLabel(self.widget_time)
        self.label_time_text.setGeometry(QtCore.QRect(40, 150, 70, 30))
        self.label_time_text.setObjectName("label_time_text")
        self.lineEdit_station = QtWidgets.QLineEdit(self.widget_time)
        self.lineEdit_station.setGeometry(QtCore.QRect(110, 150, 113, 30))
        self.lineEdit_station.setObjectName("lineEdit_station")
        self.pushButton_time_query = QtWidgets.QPushButton(self.widget_time)
        self.pushButton_time_query.setGeometry(QtCore.QRect(250, 150, 75, 30))
        self.pushButton_time_query.setObjectName("pushButton_time_query")
        self.scrollArea = QtWidgets.QScrollArea(self.widget_time)
        self.scrollArea.setGeometry(QtCore.QRect(0, 200, 951, 361))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 949, 359))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 951, 341))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.tabWidget.addTab(self.tab_time, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "火车票分析助手"))
        self.label_4.setText(_translate("MainWindow", "出发地："))
        self.label_5.setText(_translate("MainWindow", "目的地："))
        self.label_6.setText(_translate("MainWindow", "出发日："))
        self.pushButton.setText(_translate("MainWindow", "查询"))
        self.checkBox_T.setText(_translate("MainWindow", "T-特快"))
        self.checkBox_K.setText(_translate("MainWindow", "K-快速"))
        self.checkBox_Z.setText(_translate("MainWindow", "Z-直达"))
        self.checkBox_D.setText(_translate("MainWindow", "D-动车"))
        self.checkBox_G.setText(_translate("MainWindow", "GC-高铁"))
        self.label_type_2.setText(_translate("MainWindow", "车次类型："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_query), _translate("MainWindow", "车票查询"))
        self.label_7.setText(_translate("MainWindow", "出发地："))
        self.label_8.setText(_translate("MainWindow", "目的地："))
        self.pushButton_analysis_query.setText(_translate("MainWindow", "查询"))
        self.label_19.setText(_translate("MainWindow", "不紧张"))
        self.label_15.setText(_translate("MainWindow", "非常紧张"))
        self.label_17.setText(_translate("MainWindow", "紧张"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "车次"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "出发站"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "到达站"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "出发时间"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "到达时间"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "历时"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "今天"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "三天内"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "五天内"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_analysis), _translate("MainWindow", "卧铺售票分析"))
        self.label_time_text.setText(_translate("MainWindow", "起售车站："))
        self.pushButton_time_query.setText(_translate("MainWindow", "查询"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_time), _translate("MainWindow", "车票起售时间"))

import img_rc
